import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("day18_binning.csv")
df["equal_width"] = pd.cut(df["age"], bins=3)
df["equal_freq"] = pd.qcut(df["age"], q=3)
bins = [0, 18, 50, 100]
labels = ["Child", "Adult", "Senior"]
df["domain_based"] = pd.cut(df["age"], bins=bins, labels=labels)
print(df)
plt.hist(df["age"], bins=5, edgecolor="black")
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Count")
plt.show()
df["equal_width"].value_counts().sort_index().plot(kind="bar")
plt.title("Equal-Width Binning")
plt.xlabel("Bins")
plt.ylabel("Count")
plt.show()
df["equal_freq"].value_counts().sort_index().plot(kind="bar")
plt.title("Equal-Frequency Binning")
plt.xlabel("Bins")
plt.ylabel("Count")
plt.show()
df["domain_based"].value_counts().plot(kind="bar")
plt.title("Domain-Based Binning")
plt.xlabel("Category")
plt.ylabel("Count")
plt.show()